SELECT PROJECTS.ID, NAME, AVG(salary)
FROM DEVELOPERS 
JOIN DEVELOPERS_PROJECTS ON DEVELOPERS_PROJECTS.DEVELOPER_ID = DEVELOPERS.ID 
JOIN PROJECTS ON PROJECTS.ID = DEVELOPERS_PROJECTS.PROJECT_ID 
GROUP BY PROJECTS.ID 
ORDER BY PROJECTS.COST 
LIMIT 1